'use client'
import { Inter } from 'next/font/google'
import './globals.css'
//import Header from '@/components/Header';
import { NextUIProvider } from '@nextui-org/react'
import { ToastContainer, toast } from 'react-toastify';
import { store } from './store'
import { Provider } from 'react-redux'
const inter = Inter({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={inter.className} >
        <NextUIProvider >
          <Provider store={store}>
             {children}
          </Provider>
          <ToastContainer />
        </NextUIProvider>
      </body>
    </html>
  )
}